"""
Constants
"""
NER_TO_NODE_RELATIONSHIP = ["PERSON", "ORGANIZATION", "LOCATION"]
NER_LOCATION = ["CITY", "STATE_OR_PROVINCE", "COUNTRY"]

# NLP_SERVER_URL = "http://localhost:9000/"
NLP_SERVER_URL = "http://129.6.60.210:9000/"
